version: '3'

services:

  jfr-datasource:
    image: quay.io/cryostat/jfr-datasource:latest
    hostname: jfr-datasource
    expose:
      - 8080
    healthcheck:
      test: curl -k --fail http://localhost:8080
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

  grafana:
    image: quay.io/cryostat/cryostat-grafana-dashboard:latest
    hostname: grafana
    expose:
      - 3000
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - JFR_DATASOURCE_URL=http://jfr-datasource:8080
    healthcheck:
      test: wget -q --spider http://localhost:3000/api/health
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
