version: '3'

services:

  cryostat:
    image: quay.io/cryostat/cryostat:2.4.0-snapshot
    hostname: cryostat
    labels:
      - io.cryostat.discovery=true
      - io.cryostat.jmxUrl=service:jmx:rmi:///jndi/rmi://localhost:0/jmxrmi
    expose:
      - 8181
    ports:
      - '8181:8181'
    user: '0'
    tmpfs:
      - /opt/cryostat.d/recordings.d
      - /certs
      - /clientlib
      - /opt/cryostat.d/conf.d
      - /opt/cryostat.d/templates.d
      - /truststore
      - /opt/cryostat.d/conf.d/probes.d
    volumes:
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/run/user/0/podman/podman.sock:Z
    security_opt:
      - label=disable
    environment:
      - CRYOSTAT_ENABLE_JDP_BROADCAST=true
      - CRYOSTAT_PLATFORM=io.cryostat.platform.internal.DefaultPlatformStrategy,io.cryostat.platform.internal.PodmanPlatformStrategy
      - CRYOSTAT_DISABLE_SSL=true
      - CRYOSTAT_DISABLE_JMX_AUTH=${CRYOSTAT_DISABLE_JMX_AUTH:-true}
      - CRYOSTAT_ALLOW_UNTRUSTED_SSL=true
      - CRYOSTAT_RJMX_PORT=9091
      - CRYOSTAT_RMI_PORT=9091
      - CRYOSTAT_WEB_HOST=localhost
      - CRYOSTAT_WEB_PORT=8181
      - CRYOSTAT_EXT_WEB_PORT=8181
      - CRYOSTAT_AUTH_MANAGER=io.cryostat.net.NoopAuthManager
      - CRYOSTAT_CONFIG_PATH=/opt/cryostat.d/conf.d
      - CRYOSTAT_ARCHIVE_PATH=/opt/cryostat.d/recordings.d
      - CRYOSTAT_TEMPLATE_PATH=/opt/cryostat.d/templates.d
      - CRYOSTAT_PROBE_TEMPLATE_PATH=/opt/cryostat.d/conf.d/probes.d
      - CRYOSTAT_CLIENTLIB_PATH=/clientlib
      - CRYOSTAT_JDBC_DRIVER=${JDBC_DRIVER:-org.h2.Driver}
      - CRYOSTAT_JDBC_URL=${JDBC_URL:-jdbc:h2:file:/opt/cryostat.d/conf.d/h2;INIT=create domain if not exists jsonb as varchar}
      - CRYOSTAT_JDBC_USERNAME=${JDBC_USERNAME:-cryostat}
      - CRYOSTAT_HIBERNATE_DIALECT=${HIBERNATE_DIALECT:-org.hibernate.dialect.H2Dialect}
      - CRYOSTAT_HBM2DDL=${HBM2DDL:-update}
      - CRYOSTAT_JMX_CREDENTIALS_DB_PASSWORD=quarkus_test
