version: '3'

services:

  quarkus-jvm-agents:
    depends_on:
      db3:
        condition: service_healthy
    image: quay.io/andrewazores/quarkus-quickstart-hibernate:jvm-latest
    hostname: quarkus-jvm-agents
    labels:
      - io.cryostat.discovery=true
      - io.cryostat.jmxPort=9093
      - io.cryostat.jmxHost=${QUARKUS_JVM_AGENTS_JMX_HOST:-quarkus-jvm-agents}
    expose:
      - 8082
      - 9093
    ports:
      - '8082:8082'
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:postgresql://db3/quarkus_test'
      JAVA_OPTS_APPEND: >-
        -javaagent:/extras/extras/jmc-agent-1.0.1-SNAPSHOT.jar
        -Dcom.sun.management.jmxremote.autodiscovery=true
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9093
        -Dcom.sun.management.jmxremote.rmi.port=9093
        -Djava.rmi.server.hostname=quarkus-jvm-agents
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.local.only=false
    volumes:
      - cryostat_quarkus_demo:/extras
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8082/ || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

  db3:
    image: postgres:13.3
    hostname: db3
    expose:
      - 5432
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U quarkus_test -d quarkus_test || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

volumes:
  cryostat_quarkus_demo:
    external: true
