version: '3'

services:

  quarkus-jvm:
    depends_on:
      db1:
        condition: service_healthy
    image: quay.io/andrewazores/quarkus-quickstart-hibernate:jvm-latest
    hostname: quarkus-jvm
    labels:
      - io.cryostat.discovery=true
      - io.cryostat.jmxPort=9090
    expose:
      - 8080
      - 9090
    ports:
      - '8080:8080'
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:postgresql://db1/quarkus_test'
      JAVA_OPTS_APPEND: "-Dcom.sun.management.jmxremote.autodiscovery=true -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.rmi.port=9090 -Djava.rmi.server.hostname=quarkus-jvm -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

  quarkus-native:
    depends_on:
      db2:
        condition: service_healthy
    image: quay.io/andrewazores/quarkus-quickstart-hibernate:native-latest
    hostname: quarkus-native
    labels:
      - io.cryostat.discovery=true
      - io.cryostat.jmxPort=9092 # TODO, need to compile the image with this supported + enabled
    expose:
      - 8081
      - 9092
    ports:
      - '8081:8081'
    environment:
      QUARKUS_HTTP_PORT: 8081
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:postgresql://db2/quarkus_test'
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8081/ || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

  db1:
    image: postgres:13.3
    hostname: db1
    expose:
      - 5432
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U quarkus_test -d quarkus_test || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

  db2:
    image: postgres:13.3
    hostname: db2
    expose:
      - 5432
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U quarkus_test -d quarkus_test || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
