version: '3'

services:
  quarkus-jvm:
    depends_on:
      db:
        condition: service_healthy
    image: quay.io/andrewazores/quarkus-quickstart-hibernate:jvm-latest
    hostname: quarkus-jvm
    expose:
      - 8080
    ports:
      - '8080:8080'
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:postgresql://db/quarkus_test'
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

  quarkus-native:
    depends_on:
      db:
        condition: service_healthy
    image: quay.io/andrewazores/quarkus-quickstart-hibernate:native-latest
    hostname: quarkus-native
    expose:
      - 8081
    ports:
      - '8081:8081'
    environment:
      QUARKUS_HTTP_PORT: 8081
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:postgresql://db/quarkus_test'
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8081/ || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

  db:
    image: postgres:13.3
    hostname: db
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U quarkus_test -d quarkus_test || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
